version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
    #Sécuriser les identifiants de connexion
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
    #Tout ce qui est écrit dans le dossier /data/db à l'intérieur du conteneur doit être sauvegardé dans le volume nommé mongo-data à l'extérieur
    #L'image mongo:latest est configurée par ses développeurs pour stocker toutes ses données dans le dossier /data/db à l'intérieur du conteneur
      - mongo-data:/data/db
    networks:
      - my_network

  migrator:
    build:
        context: ..
        dockerfile: docker/Dockerfile
    environment:
          - MONGO_ROOT_USER=${MONGO_ROOT_USER}
          - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ../data:/app/data 
      #- ${PWD}/data:/app/data
    depends_on:
      - mongodb
    networks:
      - my_network
    #Options permettant d'interagir avec le conteneur (migrator) via le terminal
    stdin_open: true
    tty: true

volumes:
  mongo-data:

networks:
  my_network:
    driver: bridge
